title: Portafolio | Irving Fernando Rodríguez Ortega
description: Portafolio académico de Ingeniería Mecatrónica y Sistemas Ciberfísicos

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: "https://FERNXNDXRO.github.io"
baseurl: "/portafolio-just-the-docs"

just_the_docs:
  custom_css:
    - "assets/css/custom.css"
  footer_content: ""

search_enabled: true
search:
  heading_level: 2

aux_links:
  "Ver repositorio en GitHub":
    - "https://github.com/FERNXNDXRO/portafolio-just-the-docs"

permalink: pretty

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
